package com.sqisoft.plantmate.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.sqisoft.plantmate.domain.Bookmark;
import com.sqisoft.plantmate.domain.BookmarkFilter;

@Mapper
public interface BookmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @SelectProvider(type=BookmarkSqlProvider.class, method="countByExample")
    long countByExample(BookmarkFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @DeleteProvider(type=BookmarkSqlProvider.class, method="deleteByExample")
    int deleteByExample(BookmarkFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_bookmark",
        "where BOOKMARKID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_bookmark (BOOKMARKID, USER_ID, ",
        "COMMUNITYID, CREATE_DATE, ",
        "MODIFY_DATE)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=VARCHAR}, ",
        "#{communityId,jdbcType=INTEGER}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{modifyDate,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="select coalesce(max(BOOKMARKID), 0) + 1 from tb_bookmark", keyProperty="id", before=true, resultType=Integer.class)
    int insert(Bookmark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @InsertProvider(type=BookmarkSqlProvider.class, method="insertSelective")
    @SelectKey(statement="select coalesce(max(BOOKMARKID), 0) + 1 from tb_bookmark", keyProperty="id", before=true, resultType=Integer.class)
    int insertSelective(Bookmark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @SelectProvider(type=BookmarkSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="BOOKMARKID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMUNITYID", property="communityId", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_DATE", property="modifyDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Bookmark> selectByExample(BookmarkFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "BOOKMARKID, USER_ID, COMMUNITYID, CREATE_DATE, MODIFY_DATE",
        "from tb_bookmark",
        "where BOOKMARKID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="BOOKMARKID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMUNITYID", property="communityId", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_DATE", property="modifyDate", jdbcType=JdbcType.TIMESTAMP)
    })
    Bookmark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BookmarkSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Bookmark row, @Param("example") BookmarkFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BookmarkSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Bookmark row, @Param("example") BookmarkFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BookmarkSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Bookmark row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bookmark
     *
     * @mbg.generated
     */
    @Update({
        "update tb_bookmark",
        "set USER_ID = #{userId,jdbcType=VARCHAR},",
          "COMMUNITYID = #{communityId,jdbcType=INTEGER},",
          "CREATE_DATE = #{createDate,jdbcType=TIMESTAMP},",
          "MODIFY_DATE = #{modifyDate,jdbcType=TIMESTAMP}",
        "where BOOKMARKID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Bookmark row);
}