package com.sqisoft.plantmate.mapper;

import com.sqisoft.plantmate.domain.Community;
import com.sqisoft.plantmate.domain.CommunityFilter.Criteria;
import com.sqisoft.plantmate.domain.CommunityFilter.Criterion;
import com.sqisoft.plantmate.domain.CommunityFilter;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CommunitySqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    public String countByExample(CommunityFilter example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_community");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    public String deleteByExample(CommunityFilter example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_community");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    public String insertSelective(Community row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_community");
        
        sql.VALUES("COMMUNITYID", "#{id,jdbcType=INTEGER}");
        
        if (row.getTitle() != null) {
            sql.VALUES("TITLE", "#{title,jdbcType=VARCHAR}");
        }
        
        if (row.getContent() != null) {
            sql.VALUES("CONTENT", "#{content,jdbcType=VARCHAR}");
        }
        
        if (row.getCreateDate() != null) {
            sql.VALUES("CREATE_DATE", "#{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getModifyDate() != null) {
            sql.VALUES("MODIFY_DATE", "#{modifyDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCategoryId() != null) {
            sql.VALUES("CATEGORYID", "#{categoryId,jdbcType=CHAR}");
        }
        
        if (row.getFileid() != null) {
            sql.VALUES("FILEID", "#{fileid,jdbcType=INTEGER}");
        }
        
        if (row.getPlantid() != null) {
            sql.VALUES("PLANTID", "#{plantid,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    public String selectByExample(CommunityFilter example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("COMMUNITYID");
        } else {
            sql.SELECT("COMMUNITYID");
        }
        sql.SELECT("TITLE");
        sql.SELECT("CONTENT");
        sql.SELECT("CREATE_DATE");
        sql.SELECT("MODIFY_DATE");
        sql.SELECT("CATEGORYID");
        sql.SELECT("FILEID");
        sql.SELECT("PLANTID");
        sql.FROM("tb_community");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Community row = (Community) parameter.get("row");
        CommunityFilter example = (CommunityFilter) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("tb_community");
        
        if (row.getId() != null) {
            sql.SET("COMMUNITYID = #{row.id,jdbcType=INTEGER}");
        }
        
        if (row.getTitle() != null) {
            sql.SET("TITLE = #{row.title,jdbcType=VARCHAR}");
        }
        
        if (row.getContent() != null) {
            sql.SET("CONTENT = #{row.content,jdbcType=VARCHAR}");
        }
        
        if (row.getCreateDate() != null) {
            sql.SET("CREATE_DATE = #{row.createDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getModifyDate() != null) {
            sql.SET("MODIFY_DATE = #{row.modifyDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCategoryId() != null) {
            sql.SET("CATEGORYID = #{row.categoryId,jdbcType=CHAR}");
        }
        
        if (row.getFileid() != null) {
            sql.SET("FILEID = #{row.fileid,jdbcType=INTEGER}");
        }
        
        if (row.getPlantid() != null) {
            sql.SET("PLANTID = #{row.plantid,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_community");
        
        sql.SET("COMMUNITYID = #{row.id,jdbcType=INTEGER}");
        sql.SET("TITLE = #{row.title,jdbcType=VARCHAR}");
        sql.SET("CONTENT = #{row.content,jdbcType=VARCHAR}");
        sql.SET("CREATE_DATE = #{row.createDate,jdbcType=TIMESTAMP}");
        sql.SET("MODIFY_DATE = #{row.modifyDate,jdbcType=TIMESTAMP}");
        sql.SET("CATEGORYID = #{row.categoryId,jdbcType=CHAR}");
        sql.SET("FILEID = #{row.fileid,jdbcType=INTEGER}");
        sql.SET("PLANTID = #{row.plantid,jdbcType=INTEGER}");
        
        CommunityFilter example = (CommunityFilter) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Community row) {
        SQL sql = new SQL();
        sql.UPDATE("tb_community");
        
        if (row.getTitle() != null) {
            sql.SET("TITLE = #{title,jdbcType=VARCHAR}");
        }
        
        if (row.getContent() != null) {
            sql.SET("CONTENT = #{content,jdbcType=VARCHAR}");
        }
        
        if (row.getCreateDate() != null) {
            sql.SET("CREATE_DATE = #{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getModifyDate() != null) {
            sql.SET("MODIFY_DATE = #{modifyDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCategoryId() != null) {
            sql.SET("CATEGORYID = #{categoryId,jdbcType=CHAR}");
        }
        
        if (row.getFileid() != null) {
            sql.SET("FILEID = #{fileid,jdbcType=INTEGER}");
        }
        
        if (row.getPlantid() != null) {
            sql.SET("PLANTID = #{plantid,jdbcType=INTEGER}");
        }
        
        sql.WHERE("COMMUNITYID = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, CommunityFilter example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}