package com.sqisoft.plantmate.mapper;

import com.sqisoft.plantmate.domain.Community;
import com.sqisoft.plantmate.domain.CommunityFilter;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommunitySqlProvider.class, method="countByExample")
    long countByExample(CommunityFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CommunitySqlProvider.class, method="deleteByExample")
    int deleteByExample(CommunityFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_community",
        "where COMMUNITYID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_community (COMMUNITYID, TITLE, ",
        "CONTENT, CREATE_DATE, ",
        "MODIFY_DATE, CATEGORYID, ",
        "FILEID, PLANTID)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{content,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{modifyDate,jdbcType=TIMESTAMP}, #{categoryId,jdbcType=CHAR}, ",
        "#{fileid,jdbcType=INTEGER}, #{plantid,jdbcType=INTEGER})"
    })
    @SelectKey(statement="select coalesce(max(COMMUNITYID), 0) + 1 from tb_community", keyProperty="id", before=true, resultType=Integer.class)
    int insert(Community row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @InsertProvider(type=CommunitySqlProvider.class, method="insertSelective")
    @SelectKey(statement="select coalesce(max(COMMUNITYID), 0) + 1 from tb_community", keyProperty="id", before=true, resultType=Integer.class)
    int insertSelective(Community row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @SelectProvider(type=CommunitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="COMMUNITYID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TITLE", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENT", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_DATE", property="modifyDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CATEGORYID", property="categoryId", jdbcType=JdbcType.CHAR),
        @Result(column="FILEID", property="fileid", jdbcType=JdbcType.INTEGER),
        @Result(column="PLANTID", property="plantid", jdbcType=JdbcType.INTEGER)
    })
    List<Community> selectByExample(CommunityFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "COMMUNITYID, TITLE, CONTENT, CREATE_DATE, MODIFY_DATE, CATEGORYID, FILEID, PLANTID",
        "from tb_community",
        "where COMMUNITYID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="COMMUNITYID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TITLE", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENT", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_DATE", property="modifyDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CATEGORYID", property="categoryId", jdbcType=JdbcType.CHAR),
        @Result(column="FILEID", property="fileid", jdbcType=JdbcType.INTEGER),
        @Result(column="PLANTID", property="plantid", jdbcType=JdbcType.INTEGER)
    })
    Community selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommunitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Community row, @Param("example") CommunityFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommunitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Community row, @Param("example") CommunityFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CommunitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Community row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_community
     *
     * @mbg.generated
     */
    @Update({
        "update tb_community",
        "set TITLE = #{title,jdbcType=VARCHAR},",
          "CONTENT = #{content,jdbcType=VARCHAR},",
          "CREATE_DATE = #{createDate,jdbcType=TIMESTAMP},",
          "MODIFY_DATE = #{modifyDate,jdbcType=TIMESTAMP},",
          "CATEGORYID = #{categoryId,jdbcType=CHAR},",
          "FILEID = #{fileid,jdbcType=INTEGER},",
          "PLANTID = #{plantid,jdbcType=INTEGER}",
        "where COMMUNITYID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Community row);
}