package com.sqisoft.plantmate.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import com.sqisoft.plantmate.domain.MemberPlant;
import com.sqisoft.plantmate.domain.MemberPlantFilter;
import com.sqisoft.plantmate.domain.MemberPlantFilter.Criteria;
import com.sqisoft.plantmate.domain.MemberPlantFilter.Criterion;

public class MemberPlantSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member_plant
     *
     * @mbg.generated
     */
    public String countByExample(MemberPlantFilter example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_member_plant");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member_plant
     *
     * @mbg.generated
     */
    public String deleteByExample(MemberPlantFilter example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_member_plant");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member_plant
     *
     * @mbg.generated
     */
    public String insertSelective(MemberPlant row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_member_plant");
        
        sql.VALUES("PLANTID", "#{id,jdbcType=INTEGER}");
        
        if (row.getUserId() != null) {
            sql.VALUES("USER_ID", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (row.getName() != null) {
            sql.VALUES("NAME", "#{name,jdbcType=VARCHAR}");
        }
        
        if (row.getNickname() != null) {
            sql.VALUES("NICKNAME", "#{nickname,jdbcType=VARCHAR}");
        }
        
        if (row.getMemo() != null) {
            sql.VALUES("MEMO", "#{memo,jdbcType=VARCHAR}");
        }
        
        if (row.getThumbnail() != null) {
            sql.VALUES("THUMBNAIL", "#{thumbnail,jdbcType=VARCHAR}");
        }
        
        if (row.getStartDate() != null) {
            sql.VALUES("START_DATE", "#{startDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getWaterAlarm() != null) {
            sql.VALUES("WATER_ALARM", "#{waterAlarm,jdbcType=VARCHAR}");
        }
        
        if (row.getWaterCycle() != null) {
            sql.VALUES("WATER_CYCLE", "#{waterCycle,jdbcType=INTEGER}");
        }
        
        if (row.getLastWaterDate() != null) {
            sql.VALUES("LAST_WATER_DATE", "#{lastWaterDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCreateDate() != null) {
            sql.VALUES("CREATE_DATE", "#{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getModifyDate() != null) {
            sql.VALUES("MODIFY_DATE", "#{modifyDate,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member_plant
     *
     * @mbg.generated
     */
    public String selectByExample(MemberPlantFilter example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("PLANTID");
        } else {
            sql.SELECT("PLANTID");
        }
        sql.SELECT("USER_ID");
        sql.SELECT("NAME");
        sql.SELECT("NICKNAME");
        sql.SELECT("MEMO");
        sql.SELECT("THUMBNAIL");
        sql.SELECT("START_DATE");
        sql.SELECT("WATER_ALARM");
        sql.SELECT("WATER_CYCLE");
        sql.SELECT("LAST_WATER_DATE");
        sql.SELECT("CREATE_DATE");
        sql.SELECT("MODIFY_DATE");
        sql.FROM("tb_member_plant");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member_plant
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MemberPlant row = (MemberPlant) parameter.get("row");
        MemberPlantFilter example = (MemberPlantFilter) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("tb_member_plant");
        
        if (row.getId() != null) {
            sql.SET("PLANTID = #{row.id,jdbcType=INTEGER}");
        }
        
        if (row.getUserId() != null) {
            sql.SET("USER_ID = #{row.userId,jdbcType=VARCHAR}");
        }
        
        if (row.getName() != null) {
            sql.SET("NAME = #{row.name,jdbcType=VARCHAR}");
        }
        
        if (row.getNickname() != null) {
            sql.SET("NICKNAME = #{row.nickname,jdbcType=VARCHAR}");
        }
        
        if (row.getMemo() != null) {
            sql.SET("MEMO = #{row.memo,jdbcType=VARCHAR}");
        }
        
        if (row.getThumbnail() != null) {
            sql.SET("THUMBNAIL = #{row.thumbnail,jdbcType=VARCHAR}");
        }
        
        if (row.getStartDate() != null) {
            sql.SET("START_DATE = #{row.startDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getWaterAlarm() != null) {
            sql.SET("WATER_ALARM = #{row.waterAlarm,jdbcType=VARCHAR}");
        }
        
        if (row.getWaterCycle() != null) {
            sql.SET("WATER_CYCLE = #{row.waterCycle,jdbcType=INTEGER}");
        }
        
        if (row.getLastWaterDate() != null) {
            sql.SET("LAST_WATER_DATE = #{row.lastWaterDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCreateDate() != null) {
            sql.SET("CREATE_DATE = #{row.createDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getModifyDate() != null) {
            sql.SET("MODIFY_DATE = #{row.modifyDate,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member_plant
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_member_plant");
        
        sql.SET("PLANTID = #{row.id,jdbcType=INTEGER}");
        sql.SET("USER_ID = #{row.userId,jdbcType=VARCHAR}");
        sql.SET("NAME = #{row.name,jdbcType=VARCHAR}");
        sql.SET("NICKNAME = #{row.nickname,jdbcType=VARCHAR}");
        sql.SET("MEMO = #{row.memo,jdbcType=VARCHAR}");
        sql.SET("THUMBNAIL = #{row.thumbnail,jdbcType=VARCHAR}");
        sql.SET("START_DATE = #{row.startDate,jdbcType=TIMESTAMP}");
        sql.SET("WATER_ALARM = #{row.waterAlarm,jdbcType=VARCHAR}");
        sql.SET("WATER_CYCLE = #{row.waterCycle,jdbcType=INTEGER}");
        sql.SET("LAST_WATER_DATE = #{row.lastWaterDate,jdbcType=TIMESTAMP}");
        sql.SET("CREATE_DATE = #{row.createDate,jdbcType=TIMESTAMP}");
        sql.SET("MODIFY_DATE = #{row.modifyDate,jdbcType=TIMESTAMP}");
        
        MemberPlantFilter example = (MemberPlantFilter) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member_plant
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MemberPlant row) {
        SQL sql = new SQL();
        sql.UPDATE("tb_member_plant");
        
        if (row.getUserId() != null) {
            sql.SET("USER_ID = #{userId,jdbcType=VARCHAR}");
        }
        
        if (row.getName() != null) {
            sql.SET("NAME = #{name,jdbcType=VARCHAR}");
        }
        
        if (row.getNickname() != null) {
            sql.SET("NICKNAME = #{nickname,jdbcType=VARCHAR}");
        }
        
        if (row.getMemo() != null) {
            sql.SET("MEMO = #{memo,jdbcType=VARCHAR}");
        }
        
        if (row.getThumbnail() != null) {
            sql.SET("THUMBNAIL = #{thumbnail,jdbcType=VARCHAR}");
        }
        
        if (row.getStartDate() != null) {
            sql.SET("START_DATE = #{startDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getWaterAlarm() != null) {
            sql.SET("WATER_ALARM = #{waterAlarm,jdbcType=VARCHAR}");
        }
        
        if (row.getWaterCycle() != null) {
            sql.SET("WATER_CYCLE = #{waterCycle,jdbcType=INTEGER}");
        }
        
        if (row.getLastWaterDate() != null) {
            sql.SET("LAST_WATER_DATE = #{lastWaterDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getCreateDate() != null) {
            sql.SET("CREATE_DATE = #{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getModifyDate() != null) {
            sql.SET("MODIFY_DATE = #{modifyDate,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("PLANTID = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member_plant
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, MemberPlantFilter example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}