package com.sqisoft.plantmate.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.sqisoft.plantmate.domain.PlantGrowthFileFilter;
import com.sqisoft.plantmate.domain.PlantGrowthFileKey;

@Mapper
public interface PlantGrowthFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plant_growth_file
     *
     * @mbg.generated
     */
    @SelectProvider(type=PlantGrowthFileSqlProvider.class, method="countByExample")
    long countByExample(PlantGrowthFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plant_growth_file
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PlantGrowthFileSqlProvider.class, method="deleteByExample")
    int deleteByExample(PlantGrowthFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plant_growth_file
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_plant_growth_file",
        "where RECORD_ID = #{recordId,jdbcType=INTEGER}",
          "and FILEID = #{fileId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(PlantGrowthFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plant_growth_file
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_plant_growth_file (RECORD_ID, FILEID)",
        "values (#{recordId,jdbcType=INTEGER}, #{fileId,jdbcType=INTEGER})"
    })
    int insert(PlantGrowthFileKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plant_growth_file
     *
     * @mbg.generated
     */
    @InsertProvider(type=PlantGrowthFileSqlProvider.class, method="insertSelective")
    int insertSelective(PlantGrowthFileKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plant_growth_file
     *
     * @mbg.generated
     */
    @SelectProvider(type=PlantGrowthFileSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="RECORD_ID", property="recordId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FILEID", property="fileId", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<PlantGrowthFileKey> selectByExample(PlantGrowthFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plant_growth_file
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PlantGrowthFileSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") PlantGrowthFileKey row, @Param("example") PlantGrowthFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plant_growth_file
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PlantGrowthFileSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") PlantGrowthFileKey row, @Param("example") PlantGrowthFileFilter example);
}