package com.sqisoft.plantmate.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.sqisoft.plantmate.domain.UploadFile;
import com.sqisoft.plantmate.domain.UploadFileFilter;

@Mapper
public interface UploadFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @SelectProvider(type=UploadFileSqlProvider.class, method="countByExample")
    long countByExample(UploadFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @DeleteProvider(type=UploadFileSqlProvider.class, method="deleteByExample")
    int deleteByExample(UploadFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_file",
        "where FILEID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_file (FILEID, FILENAME, ",
        "FILEPATH, FILESIZE, USERFILENAME)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{path,jdbcType=VARCHAR}, #{size,jdbcType=INTEGER}, #{userfilename,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="select coalesce(max(FILEID), 0) + 1 from tb_file", keyProperty="id", before=true, resultType=Integer.class)
    int insert(UploadFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @InsertProvider(type=UploadFileSqlProvider.class, method="insertSelective")
    @SelectKey(statement="select coalesce(max(FILEID), 0) + 1 from tb_file", keyProperty="id", before=true, resultType=Integer.class)
    int insertSelective(UploadFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @SelectProvider(type=UploadFileSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="FILEID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FILENAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILEPATH", property="path", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILESIZE", property="size", jdbcType=JdbcType.INTEGER),
        @Result(column="USERFILENAME", property="userfilename", jdbcType=JdbcType.VARCHAR)
    })
    List<UploadFile> selectByExample(UploadFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "FILEID, FILENAME, FILEPATH, FILESIZE, USERFILENAME",
        "from tb_file",
        "where FILEID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="FILEID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FILENAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILEPATH", property="path", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILESIZE", property="size", jdbcType=JdbcType.INTEGER),
        @Result(column="USERFILENAME", property="userfilename", jdbcType=JdbcType.VARCHAR)
    })
    UploadFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UploadFileSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") UploadFile row, @Param("example") UploadFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UploadFileSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") UploadFile row, @Param("example") UploadFileFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UploadFileSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UploadFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    @Update({
        "update tb_file",
        "set FILENAME = #{name,jdbcType=VARCHAR},",
          "FILEPATH = #{path,jdbcType=VARCHAR},",
          "FILESIZE = #{size,jdbcType=INTEGER},",
          "USERFILENAME = #{userfilename,jdbcType=VARCHAR}",
        "where FILEID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UploadFile row);
}