package com.sqisoft.plantmate.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import com.sqisoft.plantmate.domain.UploadFile;
import com.sqisoft.plantmate.domain.UploadFileFilter;
import com.sqisoft.plantmate.domain.UploadFileFilter.Criteria;
import com.sqisoft.plantmate.domain.UploadFileFilter.Criterion;

public class UploadFileSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    public String countByExample(UploadFileFilter example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_file");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    public String deleteByExample(UploadFileFilter example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_file");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    public String insertSelective(UploadFile row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_file");
        
        sql.VALUES("FILEID", "#{id,jdbcType=INTEGER}");
        
        if (row.getName() != null) {
            sql.VALUES("FILENAME", "#{name,jdbcType=VARCHAR}");
        }
        
        if (row.getPath() != null) {
            sql.VALUES("FILEPATH", "#{path,jdbcType=VARCHAR}");
        }
        
        if (row.getSize() != null) {
            sql.VALUES("FILESIZE", "#{size,jdbcType=INTEGER}");
        }
        
        if (row.getUserfilename() != null) {
            sql.VALUES("USERFILENAME", "#{userfilename,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    public String selectByExample(UploadFileFilter example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("FILEID");
        } else {
            sql.SELECT("FILEID");
        }
        sql.SELECT("FILENAME");
        sql.SELECT("FILEPATH");
        sql.SELECT("FILESIZE");
        sql.SELECT("USERFILENAME");
        sql.FROM("tb_file");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UploadFile row = (UploadFile) parameter.get("row");
        UploadFileFilter example = (UploadFileFilter) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("tb_file");
        
        if (row.getId() != null) {
            sql.SET("FILEID = #{row.id,jdbcType=INTEGER}");
        }
        
        if (row.getName() != null) {
            sql.SET("FILENAME = #{row.name,jdbcType=VARCHAR}");
        }
        
        if (row.getPath() != null) {
            sql.SET("FILEPATH = #{row.path,jdbcType=VARCHAR}");
        }
        
        if (row.getSize() != null) {
            sql.SET("FILESIZE = #{row.size,jdbcType=INTEGER}");
        }
        
        if (row.getUserfilename() != null) {
            sql.SET("USERFILENAME = #{row.userfilename,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_file");
        
        sql.SET("FILEID = #{row.id,jdbcType=INTEGER}");
        sql.SET("FILENAME = #{row.name,jdbcType=VARCHAR}");
        sql.SET("FILEPATH = #{row.path,jdbcType=VARCHAR}");
        sql.SET("FILESIZE = #{row.size,jdbcType=INTEGER}");
        sql.SET("USERFILENAME = #{row.userfilename,jdbcType=VARCHAR}");
        
        UploadFileFilter example = (UploadFileFilter) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UploadFile row) {
        SQL sql = new SQL();
        sql.UPDATE("tb_file");
        
        if (row.getName() != null) {
            sql.SET("FILENAME = #{name,jdbcType=VARCHAR}");
        }
        
        if (row.getPath() != null) {
            sql.SET("FILEPATH = #{path,jdbcType=VARCHAR}");
        }
        
        if (row.getSize() != null) {
            sql.SET("FILESIZE = #{size,jdbcType=INTEGER}");
        }
        
        if (row.getUserfilename() != null) {
            sql.SET("USERFILENAME = #{userfilename,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("FILEID = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, UploadFileFilter example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}