package com.sqisoft.plantmate.mapper;

import com.sqisoft.plantmate.domain.User;
import com.sqisoft.plantmate.domain.UserFilter;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserSqlProvider.class, method="countByExample")
    long countByExample(UserFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @DeleteProvider(type=UserSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_user",
        "where USER_ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_user (USER_ID, USER_NAME, ",
        "USER_NICKNAME, USER_PASSWORD, ",
        "USER_EMAIL, CREATE_DATE, ",
        "MODIFY_DATE)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{modifyDate,jdbcType=TIMESTAMP})"
    })
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=UserSqlProvider.class, method="insertSelective")
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="USER_ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USER_NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_NICKNAME", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_PASSWORD", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_DATE", property="modifyDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<User> selectByExample(UserFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "USER_ID, USER_NAME, USER_NICKNAME, USER_PASSWORD, USER_EMAIL, CREATE_DATE, MODIFY_DATE",
        "from tb_user",
        "where USER_ID = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="USER_ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USER_NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_NICKNAME", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_PASSWORD", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_DATE", property="modifyDate", jdbcType=JdbcType.TIMESTAMP)
    })
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") User row, @Param("example") UserFilter example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated
     */
    @Update({
        "update tb_user",
        "set USER_NAME = #{name,jdbcType=VARCHAR},",
          "USER_NICKNAME = #{nickname,jdbcType=VARCHAR},",
          "USER_PASSWORD = #{password,jdbcType=VARCHAR},",
          "USER_EMAIL = #{email,jdbcType=VARCHAR},",
          "CREATE_DATE = #{createDate,jdbcType=TIMESTAMP},",
          "MODIFY_DATE = #{modifyDate,jdbcType=TIMESTAMP}",
        "where USER_ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User row);
}