/*
 * 
 */
package com.sqisoft.plantmate.domain;

import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_bookmark
 * 
 * @author jynius
 */
@Data
@EqualsAndHashCode(callSuper=false)
@ToString
public class Bookmark extends BookmarkKey {

	private static final long serialVersionUID = 6477457825733723290L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bookmark.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bookmark.MODIFY_DATE
     *
     * @mbg.generated
     */
    private Date modifyDate;
}