/*
 * 
 */
package com.sqisoft.plantmate.domain;

import java.io.Serializable;

import lombok.Data;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_bookmark
 * 
 * @author jynius
 */
@Data
@ToString
public class BookmarkKey implements Serializable {

	private static final long serialVersionUID = -6841771929576468252L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bookmark.BOOKMARKID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bookmark.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bookmark.COMMUNITYID
     *
     * @mbg.generated
     */
    private Integer communityId;
}