/*
 * 
 */
package com.sqisoft.plantmate.domain;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_community
 * 
 * @author jynius
 */
@Data
@ToString
public class Community implements Serializable {
	
	private static final long serialVersionUID = -6491914742239738230L;

	public static enum Category {
		
		ASK("A", "질문해요"),
		BRAG("B", "자랑해요"),
		LIVING("L", "생활정보");
		
		private String id;
		private String title;
		private Category(String id, String title) {
			this.id = id;
			this.title = title;
		}
		
		public String getId() {
			return this.id;
		}
		
		public String getTitle() {
			return this.title;
		}

		static Category of(String id) {
			
			for(Category c: values()) {
				if(c.getId().equals(id)) {
					return c;
				}
			}

			return null;
		}
	}
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_community.COMMUNITYID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_community.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_community.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_community.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_community.MODIFY_DATE
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_community.CATEGORYID
     *
     * @mbg.generated
     */
    private Category category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_community.FILEID
     *
     * @mbg.generated
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_community.PLANTID
     *
     * @mbg.generated
     */
    private Integer plantId;
    
    /**
     * @return
     */
    public String getCategoryId() {
    	return category==null? null: category.getId();
    }
    
    public void setCategoryId(String id) {
    	this.category = Category.of(id);
    }
}