/*
 * 
 */
package com.sqisoft.plantmate.domain;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_member_plant
 * 
 * @author jynius
 */
@Data
@ToString
public class MemberPlant implements Serializable {

	private static final long serialVersionUID = 6059069447333325908L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.PLANTID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.NICKNAME
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.THUMBNAIL
     *
     * @mbg.generated
     */
    private String thumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.START_DATE
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     * Database Column Remarks:
     *   Y / N (ON/OFF)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.WATER_ALARM
     *
     * @mbg.generated
     */
    private String waterAlarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.WATER_CYCLE
     *
     * @mbg.generated
     */
    private Integer waterCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.LAST_WATER_DATE
     *
     * @mbg.generated
     */
    private Date lastWaterDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member_plant.MODIFY_DATE
     *
     * @mbg.generated
     */
    private Date modifyDate;
}