/*
 * 
 */
package com.sqisoft.plantmate.domain;

import java.io.Serializable;

import lombok.Data;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_plant_growth_file
 * 
 * @author jynius
 */
@Data
@ToString
public class PlantGrowthFileKey implements Serializable {

	private static final long serialVersionUID = -6633340418220679342L;
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tb_plant_growth_file.RECORD_ID
    *
    * @mbg.generated
    */
   private Integer recordId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column tb_plant_growth_file.FILEID
    *
    * @mbg.generated
    */
   private Integer fileId;
}