package com.sqisoft.plantmate.domain;

import java.io.Serializable;

/*
 * 
 */
import lombok.Data;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_plant_record
 * 
 * @author jynius
 */
@Data
@ToString
public class PlantRecordKey implements Serializable {

	private static final long serialVersionUID = -794947485063912898L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.RECORD_ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.PLANT_ID
     *
     * @mbg.generated
     */
    private Integer plantId;
}