/*
 * 
 */
package com.sqisoft.plantmate.domain;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_plant_growth_file
 * 
 * @author jynius
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ToString
public class PlantGrowthFile extends PlantGrowthFileKey {

	private static final long serialVersionUID = -7241359397522704764L;
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_growth_file.FILEID
     *
     * @mbg.generated
     */
    private Integer fileid;
}