/*
 * 
 */
package com.sqisoft.plantmate.domain;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_plant_record
 * 
 * @author jynius
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ToString
public class PlantRecord implements Serializable {

	private static final long serialVersionUID = 5303960794210102516L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.RECORD_ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.PLANT_ID
     *
     * @mbg.generated
     */
    private Integer plantId;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.DATE
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.LENGTH
     *
     * @mbg.generated
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.LEAF_COUNT
     *
     * @mbg.generated
     */
    private Integer leafCount;

    /**
     * Database Column Remarks:
     *   씨앗,발아,성장,개화
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.GROWTH_STATUS
     *
     * @mbg.generated
     */
    private String growthStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.WATER_SUPPLY
     *
     * @mbg.generated
     */
    private Integer waterSupply;

    /**
     * Database Column Remarks:
     *   고갈성,진흙,흙
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.SOIL_TYPE
     *
     * @mbg.generated
     */
    private String soilType;

    /**
     * Database Column Remarks:
     *   화학비료,유기질비료
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.FERTILIZER_TYPE
     *
     * @mbg.generated
     */
    private String fertilizerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.TEMPERATURE
     *
     * @mbg.generated
     */
    private Integer temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.HUMIDITY
     *
     * @mbg.generated
     */
    private Integer humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.GROWTH_CONTENT
     *
     * @mbg.generated
     */
    private String growthContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plant_record.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;
}