package com.sqisoft.plantmate.domain;

import java.io.Serializable;

/*
 * 
 */
import lombok.Data;
import lombok.ToString;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_file
 * 
 * @author jynius
 */
@Data
@ToString
public class UploadFile implements Serializable {

	private static final long serialVersionUID = -4163151143435735391L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.FILEID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.FILENAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.FILEPATH
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.FILESIZE
     *
     * @mbg.generated
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.USERFILENAME
     *
     * @mbg.generated
     */
    private String userfilename;
}